server:
  port: 8081

spring:
  datasource: &base
    name: test
    url: jdbc:mysql://127.0.0.1:3306/ecity?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
form:
  datasource:
     <<: *base
     wsUrl: 192.168.8.183:1433:cole_flower
     dbType: sql
logging:
  path: log
