## 数据库配置
###数据库类型：mysql、mssql、oracle

### driverClassName
### mysql:com.mysql.jdbc.Driver
### mssql:com.microsoft.sqlserver.jdbc.SQLServerDriver
### oracle:oracle.jdbc.driver.OracleDriver

## 基础数据库配置
db: &base1
  type: mssql
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://192.168.8.183:1433;DatabaseName=cole_flower
  username: zzht
  password: zzht
  initialSize: 0
  maxActive: 200
  maxIdle: 20
  minIdle: 1


##具体的项目配置文件可以直接引用基本数据库配置
##OMS配置信息
oms:
  <<: *base1
  url: 192.168.8.183:1433:cole_flower
  type: sql

###表单配置信息
form: 
  <<: *base1
  wsUrl: 192.168.8.183:1433:cole_flower
  type: sql
  
## 工作流
flow: 
  



